### ISSUE TITLE
Audio distortion/chop on Oculus Quest after about 10 minutes of app being open

### ISSUE THREAD

**Issue by nocxtious** [GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR#77] opened 2020-10-02 18:45 UTC
Hey all,

I just started using ReLive on my Quest and I am loving it so far, the responsiveness and video and audio (for the most part!) are great, but I am running into an issue with the audio degrading over time as the app is running.  I have experienced this with Boneworks, Beat Saber, Squadrons, Space Pirate Trainer.  Basically everything will be fine audio/visual wise, but after what I would say about 10-15 minutes audio starts to break up then rapidly become nothing but extremely garbled blips every second or 2 at most, while video and input remains perfectly fine.  If I close the ReLive app on the Quest and relaunch it without any other changes, the audio comes back perfect again and everything is fine.  Its not a huge deal as I have just been pausing the game, and relaunching when this occurs, but if possible it would be nice to find a solution to this somehow!  I have looked into some of the other posts and troubleshooting and can't seem to find anything thats working for me so far.

System:
Windows 10 19041.450
Ryzen 2700X
XFX RX580 8GB (Radeon Version 20.9.2)
SteamVR 1.14.16

Openvrpaths content:
![image](https://user-images.githubusercontent.com/72276215/94958272-19448280-04a4-11eb-8199-7c9ede7d5350.png)

VR Streaming Settings:
![image](https://user-images.githubusercontent.com/72276215/94958339-38dbab00-04a4-11eb-9d76-e30436c7cff4.png)

Radeon Audio Settings:
![image](https://user-images.githubusercontent.com/72276215/94958388-4b55e480-04a4-11eb-8ff6-c45039d5c662.png)

AMDWirelessVR.log:
https://pastebin.com/nALiK1js

Please let me know if there is any other information I can provide that may help narrow down a possible solution and thank you for any time and help!

**Comment by GennadiyAMD** [comment] 2020-10-02 21:43
@nocxtious - could you please capture the app log from the headset? Here's how to do it:
1. Connect the headset to the PC with a USB cable. The headset will ask a bunch of questions about Oculus Link, casting video and allowing file access. Answer "Allow" to the one about file access, so "No" to the rest.
2. Take off the headset, open Explorer on the PC. You should see "Quest" appearing under "This PC" on the left. 
3. Navigate to _Quest\Internal shared storage\Android\data_. Under this folder create a folder named _com.amd.wirelesshmd_ and inside that folder create another one called _files_. 
4. Unzip [app.settings.zip](https://github.com/GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR/files/5320321/app.settings.zip) and place the _app.settings_ file under _Quest\Internal shared storage\Android\data\com.amd.wirelesshmd\files_.
5. Run ReLive VR and play until you hit the problem with sound.
6. You should find a log file on the headset beside _app.settings_ in _Quest\Internal shared storage\Android\data\com.amd.wirelesshmd\files_. Copy it to the PC, zip it and attach to your response (no need to share via pastebin.com - you can just drag the zip file to the line under your response where it says "Attach files by dragging & dropping, selecting or pasting them.")
7. Rename the _app.settings_ file to something else, like _app.settings.off_ to turn off logging. Don't forget this step or you will run out of space on the headset eventually.

Thanks!

**Comment by nocxtious** [comment] 2020-10-02 22:50
@GennadiyAMD Hey!  I went ahead and tried what you asked, here is the attached log:
[amf_wvr_log.zip](https://github.com/GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR/files/5320641/amf_wvr_log.zip)

I started a practice match in Squadrons and let it run for maybe 2 minutes after the initial problem started hoping that would give you some extra information.  I did take a look at the log and it looks like the timestamps only started right around when the problem started or I exited the app, I am posting this only a few minutes after testing.  Please let me know if you need any other information and thank you again for your help!

**Comment by nocxtious** [comment] 2020-10-02 23:25
I ran through the same process again and got slightly more information out of this log I think if this also helps at all: 
[amf_wvr_log_01.zip](https://github.com/GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR/files/5320728/amf_wvr_log_01.zip)

**Comment by GennadiyAMD** [comment] 2020-10-03 01:00
@nocxtious - thanks, I see what the problem is. 

Let's see if this helps: 
1. Right-click on the speaker in the bottom-right corner and select "Open Sound Settings"
2. In the Settings->Sound page find the link on the right side of the screen that says "Sound Control Panel".
3. In the window that opens after that select your default sound device (it will be marked with a green circle with a check mark) and click on the Properties button.
4. Go to the Advanced tab and change the format to "16 bit, 44100 Hz (CD Quality)". 

Please let me know how it goes. Looks like the audio clock in the PC sound card is slightly off, which leads to an accumulating error in the time stamps over time. We will look into addressing this, but my hope that changing the audio format might address this for you and could be a quick workaround until we post a proper fix.

**Comment by nocxtious** [comment] 2020-10-03 02:29
@GennadiyAMD - Hey again,

I made the change to my primary playback device and tried again: 
![image](https://user-images.githubusercontent.com/72276215/94981216-20d84b80-04e5-11eb-869f-2147044c9c0d.png)

I tried the same thing I have tried the last 2 times and while the stuttering did occur again, it was only temporary and did actually go away on its own after maybe 30 seconds to a minute.  I am attaching the 3rd log to this post if that helps any more but its more then playable as it is right now and I will try out a longer play session to see if it occurs again after it fixes its self.  Also worse case scenario I can just turn the Quest sound all the way down and just wear my usb headset on top lol.  Thank you again for the help and please let me know if there is anything else I can do try that would help you out!

Log:
[amf_wvr_log_02.zip](https://github.com/GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR/files/5320928/amf_wvr_log_02.zip)

**Comment by nocxtious** [comment] 2020-10-11 07:58
Hey just another update, I just got a new motherboard today and the problem has not happened since installing it.
Old motherboard: https://www.amazon.com/gp/product/B06XPM7FSR/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1
New motherboard: https://www.amazon.com/GIGABYTE-X570-PCIe4-0-Realtek-Motherboard/dp/B07SQJZDTX

I will let you know if it happens to come up again but so far so good, thank you again for your help!

**Comment by GennadiyAMD** [comment] 2020-10-12 05:24
@nocxtious - thanks for letting us know. This actually confirms my suspicion about the nature of the problem. There two different clocks running - one in the audio chip itself and the other is the system timer. If the oscillator in one of them is out of spec (or they are at the opposite ends of their respective tolerance ranges), it might result in audio playing just a notch slower, not something that you could hear, but enough for the error to accumulate over a longer period of time. So it is not surprising that a different motherboard would behave differently and not surprising that we never saw it ourselves.

Thanks again for reporting this, providing the logs and your patience! I'm going to close the issue for now, if you run into this problem again, please feel free to re-open it.

**Closed by GennadiyAMD** 2020-10-12 05:24 UTC
