### ISSUE TITLE
Relive still doesn't work with the latest radeon software

### ISSUE THREAD

**Issue by knightsun2010** [GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR#109] opened 2021-05-08 02:19 UTC
3600XT/6800XT/32G/quest2/win10 20H2
Render Resolution: 2704x2736
Encoder Resolution: 1832x1920
Scaling: Non-linear
Codec: HEVC
Video Bitrate: 100Mbps
Field of View: 100 100
Frame rate: 40 10000
Streaming Protocol: UDP

The above setting worked perfect until I installed the 3.1 drivers, after waiting for 2 months, it still can't work with the latest 5.1 release, I have to roll back to the 2.1 drivers. any comment will be appreciated.

**Comment by Sparkness** [comment] 2021-05-08 06:58
same problem, can only work properly with radeon driver 21.2.1.

**Comment by Niguella** [comment] 2021-05-09 07:47
This just svaed me a bunch of troubleshooting as was trying to set this up on Q2 today and not getting it to appear as a HMD in the link profile.

**Comment by eywhat** [comment] 2021-05-09 10:17
I have amd driver 5.1 and v28 on Quest and relive work perfect.

Niguella ***@***.***> schrieb am So., 9. Mai 2021, 09:47:

**Comment by GennadiyAMD** [comment] 2021-05-09 16:20
@knightsun2010 - switch to AVC - HEVC has a problem in the latest driver. AVC works well. We're working on a fix.

**Comment by knightsun2010** [comment] 2021-05-10 15:31
> @knightsun2010 - switch to AVC - HEVC has a problem in the latest driver. AVC works well. We're working on a fix.

Tried to use AVC but AVC doesn't work either

**Comment by GennadiyAMD** [comment] 2021-05-10 18:46
@knightsun2010 - is it failing the same way with AVC - a TDR with a pop-up that the graphics driver failed to respond within the allotted time frame and a subsequent crash in SteamVR? Or is it a different behavior with AVC and HEVC? We can reproduce the problem with HEVC, but AVC is working fine for us here and for other users, judging by the comments in this thread. Could you please provide more details about what you're seeing? A log from c:\Program Files (x86)\Steam\logs\AMDWirelessVR.log would be helpful too.

I see no point in cranking the render resolution that high relative to the encode resolution. The image will get scaled down to the encode resolution anyway, so you'd not get the visual quality of the 2736 pixels anyway, but a frame would take significantly longer to render.

**Comment by Sparkness** [comment] 2021-05-11 13:22
6900xt can work  with radeon driver 21.2.1. but with 5.1, relive vr on quest2 only black screen.

**Comment by GennadiyAMD** [comment] 2021-05-12 22:07
@knightsun2010, @Sparkness - There are two separate issues that exist today - HEVC may trigger a TDR and there's an issue in ReLive VR itself - for the later the fix has been submitted and will be available in 21.6.1. 

But in the meantime please use the following workaround:
1. Use AVC or Default for codec. At high bitrates like 50-100Mbps there isn't much difference in video quality between AVC and HEVC - HEVC is better at low bitrates, but at 50+Mbps - not really.
2. The black screen problem happens when render resolution is different from encode resolution AND non-linear scaling is ON. For any Navi you can set render resolution anywhere between 1600x1600 to 2100x2100 per eye (you can leave encode resolution at 0, which would make it use the render resolution numbers) and enable non-linear scaling. Higher numbers will give you a crisper image while lower numbers would offer better latency. 

Thank you very much for catching these issues!

**Comment by knightsun2010** [comment] 2021-05-13 11:12
@GennadiyAMD thank you for your explanation and workaround, glad you confirm this issue and hope it will be solved soon.

**Comment by knightsun2010** [comment] 2021-06-23 14:32
6.1 driver works now but the video quality is worse than the Feb driver, could you please help to check if the HEVC encoding is working or not? thanks.

**Comment by GennadiyAMD** [comment] 2021-06-23 14:36
@knightsun2010 - please attach your settings.json and AMDWirelessVR.log and I'll have a look. Thanks!

**Comment by knightsun2010** [comment] 2021-06-23 15:08
@GennadiyAMD Thanks for your quick response. Please find my logs and setting files.
[Feb.zip](https://github.com/GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR/files/6702966/Feb.zip)
[June.zip](https://github.com/GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR/files/6702967/June.zip)

**Comment by GennadiyAMD** [comment] 2021-06-24 05:33
@knightsun2010 - one strange thing that I see in the June archive is the discrepancy between the bitrate specified in settings.json and AMDWirelessVR.log. settings.json is configured for 100Mbps, however in the log I see this:

2021-06-23 23:55:07.668      93C [VideoPipeline]    Info: InitializeEncoder(HEVC) succeeded
2021-06-23 23:55:07.668      93C [VideoPipeline]    Info: Video bitrate (overall) changed to **50.00 Mbps**
2021-06-23 23:55:07.669      93C [VideoPipeline]    Info: HEVC Video bitrate changed to 25.00 Mbps for left eye
2021-06-23 23:55:07.669      93C [VideoPipeline]    Info: HEVC Video bitrate changed to 25.00 Mbps for right eye
2021-06-23 23:55:07.669      93C [VideoPipeline]    Info: InitializeConverter()
2021-06-23 23:55:07.709      93C [VideoPipeline]    Info: Initialize(): Codec: HEVC 
Render Resolution: 2704x2736
Encode Resolution: 1832x1920@90fps
EFC: false
Format: NV12
Bitrate: **50000000** bps
Stereo: yes
SeparateEyeProcessing: yes
Non Linear Scale Supported : yes

I cannot reproduce this on my side however - the bitrate always matches. Is it possible that settings.json and the log file were mismatched somehow when you zipped them? Could you please double-check this? Thanks!

**Comment by knightsun2010** [comment] 2021-06-24 06:09
@GennadiyAMD I also noticed this before I upload the files, I am sure the settings.json is the one I used for the June driver. but it's strange that I can't use WebUI to read the settings in settings.json, every time I open WebUI, it displays the default value, but if I check the settings.json file, the previous setting remains, and I can use WebUI to change the value. The settings.json doesn't change even after I reinstall the AMD driver.  Just change the max framerate and tried again, please check the new file. 
[settings.zip](https://github.com/GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR/files/6706674/settings.zip)
[AMDWirelessVR.zip](https://github.com/GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR/files/6706685/AMDWirelessVR.zip)

**Comment by knightsun2010** [comment] 2021-06-24 06:33
@GennadiyAMD correct one thing, the WebUI read default value after every PC reboot, not every time access it. 
Tried again
1 uninstall the current driver with DDU, reboot, delete the AMD and OpenVR folder so when installing the driver again it can generate a new settings.json file. 
2 Install 6.1 driver and select delete previous driver option
3 config the WebUI and test again, nothing change.

**Comment by knightsun2010** [comment] 2021-06-24 07:53
@GennadiyAMD FYI I upgrade my PC to B550M, 5600x, Windows 10 21H1

**Comment by GennadiyAMD** [comment] 2021-06-24 17:37
@knightsun2010 - just updated the client app, please give it a try. You should see 100Mbps now. Please let me know if this helps.

**Comment by knightsun2010** [comment] 2021-06-25 03:41
@GennadiyAMD it looks much better now, thank you very much for your help.

**Comment by GennadiyAMD** [comment] 2021-06-25 15:32
@knightsun2010 - thanks for confirming!

**Closed by GennadiyAMD** 2021-06-25 15:32 UTC
