### ISSUE TITLE
Can't connect from Oculus Go

### ISSUE THREAD

**Issue by ET3D-ET3D** [GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR#8] opened 2019-07-24 21:05 UTC
I've followed the instructions to the best of my abilities. I have Adrenaline 19.7.2 installed with a Vega 56, I've enabled ReLive, SteamVR integration and Remote Play, I have Steam installed and running in VR mode, and I set up a standing experience. I've installed the apk on my Go.

Unfortunately when I run it, all I get is a headset+WiFi icon over white background.

Both the laptop and headset are connected to the same 5GHz network.

What's missing?

**Comment by GennadiyAMD** [comment] 2019-07-24 22:31
@ET3D-ET3D - most likely the issue is related to Windows Firewall. Please go to Windows Settings->Network & Internet->Windows Firewall. Note the type of network that says "Connected" - it would be either Domain, Private or Public. Click on "Allow an app or feature through Windows Firewall" on the left. Scroll down the list and find the entry for "VR Server". Make sure you have a check box for the type of network you have and the check box on the left of "VR Server". You might have to click on the "Change Settings" button right above the list.
Chances are your network type is set to Public and when you got prompted by Windows Firewall the first time you started VR Server, Public networks were unchecked by default in the dialog box that appeared. If it's your home router, you might want to change it to Private: https://tinkertry.com/how-to-change-windows-10-network-type-from-public-to-private
Also make sure that your laptop is connected to the router with a cable, not through WiFi.

**Comment by ET3D-ET3D** [comment] 2019-07-25 16:07
Thanks. Unfortunately it looks like the network is private and the VR server is allowed on private networks. (I actually tried before I posted here to simply turn off the firewall and it didn't help. Forgot to mention it.) Also note that Windows Firewall wasn't at that place. Probably changed with Windows 10 versions.

If my laptop is connect to the router via WiFi, would that be a real problem? It would be quite inconvenient to keep it connected via cable to the router. But I'll try and see if that solves the problem.

**Comment by ET3D-ET3D** [comment] 2019-07-25 16:35
By the way, just checked and saw that the router is a 802.11n one, not ac, but I'd assume that speed would affect mostly quality of service, not whether the headset can connect at all. 300mb/s maximum should be enough for a start, I think.

**Comment by GennadiyAMD** [comment] 2019-07-25 19:01
@ET3D-ET3D - 802.11n is not going to perform well. 300Mbs is a theoretical maximum. Your real bandwidth and latency will depend on many factors like distance to the router, external interference, etc. N also has a much higher latency than AC. We have tested 802.11n and it is just not fast enough to be usable for VR streaming. If you decide to buy an AC router, make sure it has Gigabit wired LAN ports as cheaper models often have only 100Mbps ports.
Connecting your laptop over WiFi would at least double the network latency and create more collisions on the network since the headset and the PC would be actively transmitting at the same time. Cable between the PC and the router is the way to go.

As for the connection problem, please try the following first:
- Check if you can ping the headset from the PC - you can find the IP address of the headset by running 'adb shell ifconfig' on Windows command line and looking for the 'wlan0' entry in the output.
- Check if your PC and the headset are on the same IP subnet.
- Please attach the c:\Program Files (x86)\Steam\logs\AMDWirelessVR.log file.

**Comment by ET3D-ET3D** [comment] 2019-07-29 19:32
Sorry, have been too busy to continue to check this, but finally got around to it today. After failing to ping, realising that I can't ping anything, trying to solve that, and eventually restarting my router, that solved it.

Unfortunately it looks like my Go can no longer connect to the network (possibly following an update). I'll get back to you when things sort themselves out.

Thanks for all the help attempts.

**Comment by GennadiyAMD** [comment] 2019-07-29 21:03
@ET3D-ET3D - I also received an update on my Go and had no network connectivity immediately following the update. Rebooting the headset resolved it though.
Wired Gigabit PC-to-router connection and AC WiFi are definitely the way to go.

**Comment by ET3D-ET3D** [comment] 2019-07-30 06:18
WiFi didn't return on the first restart, but it did return eventually. Also all apps were under 'unknown sources' until things got sorted out. The Go probably had some work to do before it was ready.

I saw an interesting idea on Reddit, thought I'd ask your opinion: create a hotspot using the laptop's WiFi and connect the Go to that. Won't that be the best, latency-wise, as traffic would go directly between the laptop and the Go, and both are 802.11ac? If so, there won't be need to upgrade the router.

That user only asked if that would be the a good way to go (buy a USB dongle instead of an AC router), so I don't know if it works, but I think I'll try it when I get the opportunity. If you have any experience with this, I'll be happy to hear it.

**Comment by GennadiyAMD** [comment] 2019-07-30 20:31
@ET3D-ET3D - it does work, the instructions for enabling it are here: [https://support.microsoft.com/en-ca/help/4027762/windows-use-your-pc-as-a-mobile-hotspot](https://support.microsoft.com/en-ca/help/4027762/windows-use-your-pc-as-a-mobile-hotspot). Just make sure you force it to 5GHz as it goes for 2.4GHz by default. I've just tried it on a Ryzen 7 PC with built-in WiFi on the MSI B450I Gaming Plus AC motherboard. While it worked, performance was poor - I saw lots of freezes with both UDP and TCP. Your mileage might vary, I suppose, but what I saw was a far cry from a dedicated router. I'd expect a USB dongle to be worse than a NIC sitting directly on the motherboard.

Wired Ethernet accounts for only 1-2ms of latency. The efficiency of the router's software seems to make a much bigger difference here.

**Comment by ET3D-ET3D** [comment] 2019-07-31 11:07
Yeah, that worked pretty badly. But for some reason I could only create a 2.4GHz hotspot, even though I can connect to a 5GHz network without a problem.

Still, someone on that Reddit thread did say that a USB dongle worked great.

**Comment by GennadiyAMD** [comment] 2019-07-31 17:34
@ET3D-ET3D - I also initially had trouble with enabling the 5GHz hotspot. What worked for me was enabling it on the 2.4GHz channel explicitly instead of Auto, starting the hotspot, turning it off, then switching to 5GHz. Had to repeat it a few times before Windows got convinced that this was what I really wanted :) It still gives me a warning that some mobile devices might not be able to connect to it, but it now works without any additional hassle - I just turn it on.

As for USB, make sure it's a USB3 plugged into a USB3 port - USB 2.0 would most definitely lack bandwidth. I'd also look for one with antennas.

**Comment by ET3D-ET3D** [comment] 2019-08-01 18:39
Unfortunately this solution didn't work for me. I also searched for other solutions, and they didn't work. People said that it's a legal issue with Intel WiFi controllers.

Hopefully the USB dongle will work better.

By the way, thanks for all the help and suggestions. I really appreciate them.

**Comment by GennadiyAMD** [comment] 2019-08-01 18:49
@ET3D-ET3D - you're welcome. Please post if you get it working - it's good info to know.

I'm going to close this issue for the time being since it's really not a ReLive VR problem, but feel free to reopen it if you need to add any comments to the thread.

**Closed by GennadiyAMD** 2019-08-01 18:49 UTC
