### ISSUE TITLE
Relive vr apk frequently not responding

### ISSUE THREAD

**Issue by Apples55** [GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR#90] opened 2021-01-15 19:28 UTC
Hi,

I'm using Relive vr for streaming on my Quest 2. It works great most of the time, but often the app in the headset will freeze. It's usually on loading screens or right after I load into a game (sometimes it's mid game though). It takes 30-60 seconds to unfreeze (or I just quit the app and start it again). I know it's the app on the quest 2 as looking at my pc monitor steamvr is still tracking where I look and move like normal. I'm using the latest drivers and apk and also have a good local network setup (AX-10 router AP)

Is this a known issue and is there anything I can do to fix this?

Thanks a lot for your time

**Comment by GennadiyAMD** [comment] 2021-01-16 05:26
@Apples55 - please attach a log located in c:\Program Files (x86)\Steam\logs\AMDWirelessVR.log

Your issue is most likely caused by network congestion. Have you tried any of the suggestions outlined in the [Troubleshooting](https://github.com/GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR/wiki/Troubleshooting) and in the [Advanced Network Setup](https://github.com/GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR/wiki/Advanced-Network-Setup) sections of our Wiki?

**Comment by Apples55** [comment] 2021-01-17 17:07
[AMDWirelessVR.log](https://github.com/GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR/files/5826475/AMDWirelessVR.log)
Apologies for not including this earlier. I'm new to Github and didn't realise all that would be in the wiki section. I've changed the bitrate and made some changes to my routers (they were both on 80Mhz, now on 40Mhz in different bands) and it's helped the issue a lot. Like you said it appears it's my network and not the apk. Sorry to waste your time and thanks for the help

**Comment by GennadiyAMD** [comment] 2021-01-19 05:10
@Apples55 - which GPU do you have? Is it a Polaris-based (RX470/480/580/590)? If yes, I'd highly recommend switching the codec to hevc (or leave it on auto, hevc would be selected for these architectures automatically). I see that encoding is a little slow (~15-16ms), hevc is a little faster - you'd get a slightly better latency this way.

**Comment by Apples55** [comment] 2021-01-20 16:03
@GennadiyAMD I have a vega 56. I think it's on AVC (h.264) automatically, I tried HEVC and had issues (frame drops and more latency) but I have heard HEVC tends to work better with amd cards so I might try experimenting with this a bit more. I might also try messing with datagramsize. But right now it is playable anyway
Thanks!

**Comment by GennadiyAMD** [comment] 2021-01-20 17:04
Vega56 shouldn't be a problem for either AVC or HEVC. HEVC works better only on the Polaris family - that's why I asked which GPU you had. Your problems with HEVC were likely due to network problems that you have already resolved - it tends to produce more spikes in bandwidth compared to AVC where it is a bit more uniform, so those spikes were more likely to cause frame drops on poor connections. But still, I'm seeing encode time that is a bit too high. Make sure you have the latest driver and check if the card has adequate cooling - this might be a sign of power management kicking in - say, if the fan on the card is seizing up due to dust, or the overall high temperature in the case. At 1440x1440 per eye you should see roughly 12-13ms encode time and I saw 15-16ms in the log.

I'm gonna close this issue for now, but if you have any issues, please feel free to open a new one or re-open this.

**Closed by GennadiyAMD** 2021-01-20 17:04 UTC
