### ISSUE TITLE
Audio intermittent

### ISSUE THREAD

**Issue by katoneyuki** [GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR#25] opened 2019-11-06 00:51 UTC
Thank you. relive is very convenient。
but playing the game for a while，Audio becomes intermittent，audio only。Please help me thanks。

**Comment by GennadiyAMD** [comment] 2019-11-06 15:57
@katoneyuki - which version of the AMD driver are you using? We had a bug that would cause symptoms similar to what you're describing which was fixed in one of the recent driver releases. Please try updating to the latest available at [https://www.amd.com/en/support](https://www.amd.com/en/support). If this doesn't solve the issue, please let us know and we'll debug it further.

**Comment by katoneyuki** [comment] 2019-11-07 15:03
Thanks for your reply.it didn't work.My AMD driver is 19.11.1.  Radeon RX Vega56   HMD：Oculus Quest.  ReLiveVR-Oculus-1.0.18.apk。5G WIFI
I have a new discovery.restart“ReLiveVR”Android program，temporal recovery。But after a while BUG again

**Comment by GennadiyAMD** [comment] 2019-11-07 21:18
@katoneyuki - could you please attach the log located in c:\Program Files (x86)\Steam\logs\AMDWirelessVR.log?

Thanks!

**Comment by katoneyuki** [comment] 2019-11-09 07:57
https://drive.google.com/file/d/1CcV-VLz2sZDO8AMWsB9Z3mxXyYT4kI7a/view?usp=sharing

**Comment by GennadiyAMD** [comment] 2019-11-11 22:42
@katoneyuki - could you please try a test build of the driver, see if it resolves your issue: [https://www.dropbox.com/s/3q3ewy9y79xl2tc/driver_amdwvr.dll?dl=0](https://www.dropbox.com/s/3q3ewy9y79xl2tc/driver_amdwvr.dll?dl=0)

Steps to update:
1. Make sure SteamVR is NOT running
2. Navigate to c:\Program Files\AMD\WVR\OpenVR\bin\win64
3. Rename driver_amdwvr.dll to driver_amdwvr.dll.org
4. Download the new DLL to the desktop first and then drag it to c:\Program Files\AMD\WVR\OpenVR\bin\win64
5. Start SteamVR and observe if the issue is still repeatable.

Thank you very much for your help! Please let us know if this resolves/improves the issue.

**Comment by katoneyuki** [comment] 2019-11-12 04:36
I'm sorry，It doesn't work.I just need to go back from the main menu to solve the problem.But it won't last long.The problem may be within oculus Quest
Maybe I am Individual examples.I decided to use Bluetooth headset.ReLive is Very smooth, very little delay,I can't give up.I think it's better than Virtual Desktop.Thank you for your help。AMD yes！

**Comment by GennadiyAMD** [comment] 2019-11-20 21:58
@katoneyuki - please try the latest APK (1.0.19), we have made some fixes that might resolve your issue. Please let us know if this build works. Thanks a lot!

**Comment by katoneyuki** [comment] 2019-11-22 09:57
@GennadiyAMD Audio has been fixed,Thank you for the new version，It's great！The music is smooth.Although the effect sound has some delay, but I have been satisfied！

**Comment by GennadiyAMD** [comment] 2019-11-22 14:54
@katoneyuki - thanks for confirming the fix! Unfortunately some delay in audio is inevitable as we have to buffer some data for smooth playback. Unlike video, with audio one can't repeat the last sample when the new sample hasn't arrived in time - you would hear that right away.

If you experience any further issues, please don't hesitate to let us know. Otherwise I will close the issue in a few days if nothing new is reported. Thanks for your time and help with this!

**Closed** 2019-12-11 22:56 UTC
